-   id: dead
    name: detect dead code
    description: dead simple python dead code detection
    entry: dead
    pass_filenames: false
    language: python
    language_version: python3
    types: [python]
